In [72]:
import pandas as pd
import numpy as np

data = pd.read_csv('data_for_model.csv')
data.head()

,Unnamed: 0,below_b_rating,b_rating,tag,bbb_rating,portfolio_industrials_allocation,portfolio_tech_allocation,portfolio_materials_basic_allocation,portfolio_energy_allocation,portfolio_healthcare_allocation,...,10yrs_treynor_ratio_category,10_years_return_fund,10_years_alpha_category,3yrs_treynor_ratio_fund,3_years_alpha_fund,3yrs_sharpe_ratio_fund,3_years_alpha_category,5_years_return_mean_annual_category,5_years_return_fund,5_years_alpha_category
0,0,0.00,0.00,134783,0.00,9.97,35.51,2.86,0.38,14.41,...,0.15,17.25,-0.01,12.20,0.07,1.06,0.01,0.01,11.71,-0.00
1,1,0.00,0.00,61271,0.00,11.45,25.09,8.36,0.00,16.47,...,0.15,16.21,-0.01,17.88,4.32,1.46,0.01,0.01,12.78,-0.00
2,2,0.00,0.00,64412,0.00,10.91,0.16,2.22,6.79,9.00,...,0.14,14.12,-0.02,7.93,-2.73,0.68,-0.02,0.01,7.25,-0.03
3,3,0.00,0.00,249560,0.00,16.76,9.82,15.64,0.00,0.00,...,0.09,10.77,0.00,8.09,1.51,1.12,0.01,0.01,5.65,-0.00
4,4,0.78,21.07,202778,32.55,14.69,16.73,2.35,7.76,15.77,...,0.06,3.90,-0.01,0.52,-1.85,0.06,-0.02,0.00,1.64,-0.01

In [73]:
data.drop(columns=['Unnamed: 0'],inplace=True)

log transformation to remove outliers

In [86]:
x=data.columns
for i in range(0,len(x)):
    o=data[x[i]][data[x[i]]==0]
    if (len(o)!=0):
        print(x[i])

below_b_rating
b_rating
bbb_rating
portfolio_industrials_allocation
portfolio_tech_allocation
portfolio_materials_basic_allocation
portfolio_energy_allocation
portfolio_healthcare_allocation
portfolio_property_allocation
portfolio_cyclical_consumer_allocation
yield
return_ytd
fund_ratio_net_annual_expense
pb_ratio
ps_ratio
mmc
pc_ratio
pe_ratio
cash_percent_of_portfolio
1_year_return_fund
portfolio_convertable
portfolio_others
fund_return_3years
2018_return_fund
1_month_fund_return
bond_percentage_of_porfolio
portfolio_preferred
10yrs_treynor_ratio_category
10_years_return_fund
10_years_alpha_category
3yrs_treynor_ratio_fund
3_years_alpha_fund
3yrs_sharpe_ratio_fund
3_years_alpha_category
5_years_return_mean_annual_category
5_years_return_fund
5_years_alpha_category

In [74]:
data=data.replace(0,1)

In [89]:
x=data.columns
for i in range(0,len(x)):
    o=data[x[i]][data[x[i]]==0]
    if (len(o)!=0):
        print(x[i])

In [90]:
data.dtypes

below_b_rating                            float64
b_rating                                  float64
tag                                         int64
bbb_rating                                float64
portfolio_industrials_allocation          float64
portfolio_tech_allocation                 float64
portfolio_materials_basic_allocation      float64
portfolio_energy_allocation               float64
portfolio_healthcare_allocation           float64
portfolio_property_allocation             float64
portfolio_cyclical_consumer_allocation    float64
fund_id                                    object
total_assets                              float64
yield                                     float64
greatstone_rating                         float64
return_ytd                                float64
fund_ratio_net_annual_expense             float64
pb_ratio                                  float64
ps_ratio                                  float64
mmc                                       float64
pc_ratio                                  float64
pe_ratio                                  float64
years_up                                  float64
2018_return_category                      float64
cash_percent_of_portfolio                 float64
years_down                                float64
1_year_return_fund                        float64
portfolio_convertable                     float64
portfolio_others                          float64
fund_return_3years                        float64
2018_return_fund                          float64
1_month_fund_return                       float64
bond_percentage_of_porfolio               float64
portfolio_preferred                       float64
10yrs_treynor_ratio_category              float64
10_years_return_fund                      float64
10_years_alpha_category                   float64
3yrs_treynor_ratio_fund                   float64
3_years_alpha_fund                        float64
3yrs_sharpe_ratio_fund                    float64
3_years_alpha_category                    float64
5_years_return_mean_annual_category       float64
5_years_return_fund                       float64
5_years_alpha_category                    float64
dtype: object

In [75]:
data['tag']=data['tag'].astype('object')
data['greatstone_rating']=data['greatstone_rating'].astype('category')
data.dtypes

below_b_rating                             float64
b_rating                                   float64
tag                                         object
bbb_rating                                 float64
portfolio_industrials_allocation           float64
portfolio_tech_allocation                  float64
portfolio_materials_basic_allocation       float64
portfolio_energy_allocation                float64
portfolio_healthcare_allocation            float64
portfolio_property_allocation              float64
portfolio_cyclical_consumer_allocation     float64
fund_id                                     object
total_assets                               float64
yield                                      float64
greatstone_rating                         category
return_ytd                                 float64
fund_ratio_net_annual_expense              float64
pb_ratio                                   float64
ps_ratio                                   float64
mmc                                        float64
pc_ratio                                   float64
pe_ratio                                   float64
years_up                                   float64
2018_return_category                       float64
cash_percent_of_portfolio                  float64
years_down                                 float64
1_year_return_fund                         float64
portfolio_convertable                      float64
portfolio_others                           float64
fund_return_3years                         float64
2018_return_fund                           float64
1_month_fund_return                        float64
bond_percentage_of_porfolio                float64
portfolio_preferred                        float64
10yrs_treynor_ratio_category               float64
10_years_return_fund                       float64
10_years_alpha_category                    float64
3yrs_treynor_ratio_fund                    float64
3_years_alpha_fund                         float64
3yrs_sharpe_ratio_fund                     float64
3_years_alpha_category                     float64
5_years_return_mean_annual_category        float64
5_years_return_fund                        float64
5_years_alpha_category                     float64
dtype: object

In [76]:
data['below_b_rating'] =data['below_b_rating'].apply(lambda x: x+2.0)
data['b_rating'] =data['b_rating'].apply(lambda x: x+2.0)

data['return_ytd'] =data['return_ytd'].apply(lambda x: x+26.0)
data['2018_return_category'] =data['2018_return_category'].apply(lambda x: x+29.0)

data['1_year_return_fund'] =data['1_year_return_fund'].apply(lambda x: x+38.0)
data['fund_return_3years'] =data['fund_return_3years'].apply(lambda x: x+29.0)

data['2018_return_fund'] =data['2018_return_fund'].apply(lambda x: x+61.0)
data['1_month_fund_return'] =data['1_month_fund_return'].apply(lambda x: x+15.0)

data['10yrs_treynor_ratio_category'] =data['10yrs_treynor_ratio_category'].apply(lambda x: x+2.0)
data['10_years_return_fund'] =data['10_years_return_fund'].apply(lambda x: x+36.0)

data['10_years_alpha_category'] =data['10_years_alpha_category'].apply(lambda x: x+2.0)
data['3yrs_treynor_ratio_fund'] =data['3yrs_treynor_ratio_fund'].apply(lambda x: x+4147.0)

data['3_years_alpha_fund'] =data['3_years_alpha_fund'].apply(lambda x: x+37.0)
data['3yrs_sharpe_ratio_fund'] =data['3yrs_sharpe_ratio_fund'].apply(lambda x: x+6.0)

data['3_years_alpha_category'] =data['3_years_alpha_category'].apply(lambda x: x+2.0)
data['5_years_return_mean_annual_category'] =data['5_years_return_mean_annual_category'].apply(lambda x: x+2.0)

data['5_years_return_fund'] =data['5_years_return_fund'].apply(lambda x: x+25.0)
data['5_years_alpha_category'] =data['5_years_alpha_category'].apply(lambda x:x+2.0)

In [77]:
data_log = pd.DataFrame()
df_x =data[data.select_dtypes(include=['int32','int64','float64','float32']).columns]
x=df_x.columns
for i in range(0,len(x)):
    data_log['log_'+x[i]] = np.log(data[x[i]])

In [78]:
data_log.head()

,log_below_b_rating,log_b_rating,log_bbb_rating,log_portfolio_industrials_allocation,log_portfolio_tech_allocation,log_portfolio_materials_basic_allocation,log_portfolio_energy_allocation,log_portfolio_healthcare_allocation,log_portfolio_property_allocation,log_portfolio_cyclical_consumer_allocation,...,log_10yrs_treynor_ratio_category,log_10_years_return_fund,log_10_years_alpha_category,log_3yrs_treynor_ratio_fund,log_3_years_alpha_fund,log_3yrs_sharpe_ratio_fund,log_3_years_alpha_category,log_5_years_return_mean_annual_category,log_5_years_return_fund,log_5_years_alpha_category
0,1.098612,1.098612,0.000000,2.299581,3.569814,1.050822,-0.967584,2.667922,0.982078,2.855320,...,0.765468,3.974998,0.688135,8.333078,3.612808,1.954445,0.698135,0.698135,3.603049,1.098612
1,1.098612,1.098612,0.000000,2.437990,3.222469,2.123458,0.000000,2.801541,0.029559,1.958685,...,0.765468,3.955274,0.688135,8.334443,3.721347,2.009555,0.698135,0.698135,3.631780,1.098612
2,1.098612,1.098612,0.000000,2.389680,-1.832581,0.797507,1.915451,2.197225,0.000000,1.691939,...,0.760806,3.914420,0.683097,8.332051,3.534270,1.899118,0.683097,0.698135,3.473518,0.678034
3,1.098612,1.098612,0.000000,2.818995,2.284421,2.749832,0.000000,0.000000,0.000000,0.000000,...,0.737164,3.845242,1.098612,8.332089,3.650918,1.962908,0.698135,0.698135,3.422633,1.098612
4,1.022451,3.138533,3.482777,2.687167,2.817204,0.854415,2.048982,2.758109,1.247032,2.221375,...,0.722706,3.686376,0.688135,8.330266,3.559625,1.801710,0.683097,1.098612,3.282414,0.688135

In [79]:
data_log['greatstone_rating']=data['greatstone_rating']

In [80]:
data_log.describe(include='all')

,log_below_b_rating,log_b_rating,log_bbb_rating,log_portfolio_industrials_allocation,log_portfolio_tech_allocation,log_portfolio_materials_basic_allocation,log_portfolio_energy_allocation,log_portfolio_healthcare_allocation,log_portfolio_property_allocation,log_portfolio_cyclical_consumer_allocation,...,log_10_years_return_fund,log_10_years_alpha_category,log_3yrs_treynor_ratio_fund,log_3_years_alpha_fund,log_3yrs_sharpe_ratio_fund,log_3_years_alpha_category,log_5_years_return_mean_annual_category,log_5_years_return_fund,log_5_years_alpha_category,greatstone_rating
count,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,...,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.000000,18491.0
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6744.0
mean,1.180945,1.393008,0.939439,1.653534,1.862893,0.918928,1.059649,1.560649,0.783322,1.676754,...,3.762907,0.772549,8.331379,3.590958,1.898913,0.779018,0.934494,3.377177,0.810587,NaN
std,0.340337,0.685821,1.338340,1.256935,1.429417,0.988207,1.147501,1.292806,1.148689,1.258829,...,0.135452,0.161031,0.060269,0.098836,0.068059,0.169020,0.197044,0.140581,0.189108,NaN
min,0.683097,0.631272,-3.912023,-4.605170,-4.605170,-4.605170,-4.605170,-4.605170,-4.605170,-4.605170,...,2.832625,0.636577,0.165514,0.559616,1.147402,0.631272,0.688135,0.405465,0.598837,NaN
25%,1.098612,1.098612,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.610918,0.683097,8.330893,3.552487,1.864080,0.688135,0.698135,3.290266,0.683097,NaN
50%,1.098612,1.098612,0.000000,2.259678,2.548664,1.026042,1.241269,2.242835,0.438255,2.347558,...,3.763987,0.698135,8.331620,3.595118,1.908060,0.688135,1.098612,3.369018,0.698135,NaN
75%,1.098612,1.098612,2.442347,2.552565,2.983153,1.625311,1.849242,2.613007,1.486140,2.585506,...,3.887525,0.722706,8.332479,3.634687,1.941615,0.717840,1.098612,3.457578,1.098612,NaN
max,3.790985,4.414978,4.584967,4.605170,4.605170,4.605170,4.605170,4.605170,4.605170,4.605170,...,4.339380,1.098612,8.688290,4.028027,2.318458,1.098612,1.098612,3.994340,1.098612,NaN

In [10]:
X = data_log.drop(columns=['greatstone_rating'])
y = data_log['greatstone_rating']
print(X.shape)
print(y.shape)

(18491, 41)
(18491,)

In [11]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(12943, 41)
(12943,)
(5548, 41)
(5548,)

In [99]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors= 5 , weights = 'distance' )

In [100]:
KNN.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='distance')

In [101]:
predicted_val_labels = KNN.predict(X_test)
KNN.score(X_test, y_test)

0.5762436914203316

In [102]:
from sklearn import metrics

print(metrics.confusion_matrix(y_test, predicted_val_labels))

[[ 191  120   54   14    4]
 [  82  689  387   77   16]
 [  24  301 1323  345   51]
 [  15   77  435  744  106]
 [   5   27   71  140  250]]

In [104]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

myList = list(range(1,50))

cv_scores = []
k_neighbors = []

for k in myList:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train, y_train, cv=10, scoring='accuracy')
    cv_scores.append(scores.mean())
    k_neighbors.append(k)
    
best_k = myList[cv_scores.index(max(cv_scores))]
print ("The optimal number of neighbors is %d" % best_k)

The optimal number of neighbors is 1

In [112]:
KNN_1=KNeighborsClassifier(n_neighbors=1 , weights = 'uniform' )
KNN_1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [113]:
KNN_1.score(X_test, y_test)

0.5962509012256669

In [81]:
data_test = pd.read_csv('test1.csv')
data_test.head()

,Unnamed: 0,bb_rating,us_govt_bond_rating,below_b_rating,others_rating,b_rating,tag,a_rating,aaa_rating,aa_rating,...,3_years_return_category,category_r_squared_5years,5yrs_sharpe_ratio_category,5_years_return_mean_annual_category,5yrs_treynor_ratio_category,5_years_return_fund,5_years_alpha_category,5_years_beta_category,5years_category_std,5_years_return_category
0,0,0.00,0.0,0.0,0.00,0.00,67922,0.00,0.00,0.00,...,7.36,0.51,-0.00,-0.00,-0.04,0.00,-0.11,0.01,0.20,-4.25
1,1,0.00,0.0,0.0,0.00,0.00,138257,0.00,0.00,0.00,...,10.01,0.86,0.01,0.01,0.07,0.00,-0.03,0.01,0.11,7.20
2,2,0.00,0.0,0.0,0.00,0.00,191978,0.00,0.00,0.00,...,15.88,0.65,0.01,0.01,0.06,6.54,-0.03,0.01,0.17,8.45
3,3,5.33,0.0,0.0,0.04,0.98,105506,35.19,2.79,5.78,...,9.94,0.95,0.01,0.01,0.04,7.10,-0.01,0.01,0.10,6.41
4,4,0.80,0.0,0.0,22.80,0.90,58517,27.00,7.20,22.10,...,1.11,0.66,0.00,0.00,0.04,1.09,-0.01,0.00,0.01,1.14

In [82]:
data.columns

Index(['below_b_rating', 'b_rating', 'tag', 'bbb_rating',
       'portfolio_industrials_allocation', 'portfolio_tech_allocation',
       'portfolio_materials_basic_allocation', 'portfolio_energy_allocation',
       'portfolio_healthcare_allocation', 'portfolio_property_allocation',
       'portfolio_cyclical_consumer_allocation', 'fund_id', 'total_assets',
       'yield', 'greatstone_rating', 'return_ytd',
       'fund_ratio_net_annual_expense', 'pb_ratio', 'ps_ratio', 'mmc',
       'pc_ratio', 'pe_ratio', 'years_up', '2018_return_category',
       'cash_percent_of_portfolio', 'years_down', '1_year_return_fund',
       'portfolio_convertable', 'portfolio_others', 'fund_return_3years',
       '2018_return_fund', '1_month_fund_return',
       'bond_percentage_of_porfolio', 'portfolio_preferred',
       '10yrs_treynor_ratio_category', '10_years_return_fund',
       '10_years_alpha_category', '3yrs_treynor_ratio_fund',
       '3_years_alpha_fund', '3yrs_sharpe_ratio_fund',
       '3_years_alpha_category', '5_years_return_mean_annual_category',
       '5_years_return_fund', '5_years_alpha_category'],
      dtype='object')

In [83]:
data_test = data_test[['below_b_rating', 'b_rating', 'tag', 'bbb_rating',
       'portfolio_industrials_allocation', 'portfolio_tech_allocation',
       'portfolio_materials_basic_allocation', 'portfolio_energy_allocation',
       'portfolio_healthcare_allocation', 'portfolio_property_allocation',
       'portfolio_cyclical_consumer_allocation', 'fund_id', 'total_assets',
       'yield', 'greatstone_rating', 'return_ytd',
       'fund_ratio_net_annual_expense', 'pb_ratio', 'ps_ratio', 'mmc',
       'pc_ratio', 'pe_ratio', 'years_up', '2018_return_category',
       'cash_percent_of_portfolio', 'years_down', '1_year_return_fund',
       'portfolio_convertable', 'portfolio_others', 'fund_return_3years_x',
       '2018_return_fund', '1_month_fund_return',
       'bond_percentage_of_porfolio', 'portfolio_preferred',
       '10yrs_treynor_ratio_category', '10_years_return_fund',
       '10_years_alpha_category', '3yrs_treynor_ratio_fund',
       '3_years_alpha_fund', '3yrs_sharpe_ratio_fund',
       '3_years_alpha_category', '5_years_return_mean_annual_category',
       '5_years_return_fund', '5_years_alpha_category']]

In [84]:
data_test.rename(columns={'fund_return_3years_x':'fund_return_3years'},inplace=True)
data_test.shape

(5000, 44)

In [85]:
data_test_1 =data_test.drop(columns=['tag','fund_id','greatstone_rating'])

In [86]:
import re
data_test_1['mmc']=data_test_1['mmc'].apply(lambda x: re.sub(',','',str(x)))
data_test_1['pc_ratio']=data_test_1['pc_ratio'].apply(lambda x: re.sub(',','',str(x)))
data_test_1['pe_ratio']=data_test_1['pe_ratio'].apply(lambda x: re.sub(',','',str(x)))
data_test_1['3yrs_treynor_ratio_fund']=data_test_1['3yrs_treynor_ratio_fund'].apply(lambda x: re.sub(',','',str(x)))

In [87]:
data_test_1['mmc']=data_test_1['mmc'].astype('float64')
data_test_1['pc_ratio']=data_test_1['pc_ratio'].astype('float64')
data_test_1['pe_ratio']=data_test_1['pe_ratio'].astype('float64')
data_test_1['3yrs_treynor_ratio_fund']=data_test_1['3yrs_treynor_ratio_fund'].astype('float64')

In [88]:
def fill_mis(df):
    total = df.isnull().sum().sort_values(ascending=False)
    mis_data=pd.DataFrame(total).reset_index()
    mis_data.columns=['Features','Total']
    x=np.array(mis_data['Features'][mis_data['Total']>0])
    for i in range(0,len(x)):
        mean = df[x[i]].mean()
        median = df[x[i]].median()
        std = df[x[i]].std()
        if std >10:
            df[x[i]]=df[x[i]].fillna(median)
        else:
            df[x[i]]=df[x[i]].fillna(mean)

In [89]:
fill_mis(data_test_1)

In [90]:
data_test_1.shape

(5000, 41)

In [71]:
data_test_1['3yrs_sharpe_ratio_fund'].sort_values().head(10)

2661   -4.39
1461   -3.19
3324   -2.72
3091   -2.27
715    -2.22
4303   -2.13
28     -2.06
731    -2.06
2739   -1.91
288    -1.84
Name: 3yrs_sharpe_ratio_fund, dtype: float64

In [91]:
data_test_1['below_b_rating'] =data_test_1['below_b_rating'].apply(lambda x: x+2.0)
data_test_1['b_rating'] =data_test_1['b_rating'].apply(lambda x: x+2.0)

data_test_1['return_ytd'] =data_test_1['return_ytd'].apply(lambda x: x+26.0)##
data_test_1['2018_return_category'] =data_test_1['2018_return_category'].apply(lambda x: x+29.0)

data_test_1['1_year_return_fund'] =data_test_1['1_year_return_fund'].apply(lambda x: x+38.0)
data_test_1['fund_return_3years'] =data_test_1['fund_return_3years'].apply(lambda x: x+29.0)##

data_test_1['2018_return_fund'] =data_test_1['2018_return_fund'].apply(lambda x: x+61.0)##
data_test_1['1_month_fund_return'] =data_test_1['1_month_fund_return'].apply(lambda x: x+15.0)

data_test_1['10yrs_treynor_ratio_category'] =data_test_1['10yrs_treynor_ratio_category'].apply(lambda x: x+2.0)
data_test_1['10_years_return_fund'] =data_test_1['10_years_return_fund'].apply(lambda x: x+36.0)##

data_test_1['10_years_alpha_category'] =data_test_1['10_years_alpha_category'].apply(lambda x: x+2.0)
data_test_1['3yrs_treynor_ratio_fund'] =data_test_1['3yrs_treynor_ratio_fund'].apply(lambda x: x+4147.0)

data_test_1['3_years_alpha_fund'] =data_test_1['3_years_alpha_fund'].apply(lambda x: x+37.0)
data_test_1['3yrs_sharpe_ratio_fund'] =data_test_1['3yrs_sharpe_ratio_fund'].apply(lambda x: x+6.0)##

data_test_1['3_years_alpha_category'] =data_test_1['3_years_alpha_category'].apply(lambda x: x+2.0)
data_test_1['5_years_return_mean_annual_category'] =data_test_1['5_years_return_mean_annual_category'].apply(lambda x: x+2.0)

data_test_1['5_years_return_fund'] =data_test_1['5_years_return_fund'].apply(lambda x: x+25.0)
data_test_1['5_years_alpha_category'] =data_test_1['5_years_alpha_category'].apply(lambda x:x+2.0)

In [95]:
data_test_1=data_test_1.replace(0,1)

In [96]:
data_test_log = pd.DataFrame()
df_x =data_test_1[data_test_1.select_dtypes(include=['int32','int64','float64','float32']).columns]
x=df_x.columns
for i in range(0,len(x)):
    data_test_log['log_'+x[i]] = np.log(data_test_1[x[i]])

In [99]:
data_test_log.shape

(5000, 41)

In [104]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors= 1 , weights = 'distance' )

In [100]:
X_train = data_log.drop(columns=['greatstone_rating'])
y_train = data_log['greatstone_rating']
X_test = data_test_log

In [101]:
X_train.shape

(18491, 41)

In [102]:
y_train.shape

(18491,)

In [103]:
X_test.shape

(5000, 41)

In [105]:
KNN.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='distance')

In [106]:
predicted_val_labels = KNN.predict(X_test)

In [108]:
len(predicted_val_labels)

5000

In [111]:
result=pd.DataFrame()
result['fund_id']=data_test['fund_id']
result['greatstone_rating']=predicted_val_labels

In [112]:
result.head()

                                fund_id  greatstone_rating
0  264614c6-5ac3-4146-ba26-1674b136cb40                2.0
1  08702e4f-c5bb-4f0a-b63b-f9e4a0eb2425                4.0
2  cf56db43-046b-49d0-b8f0-90fe9cf8aacf                2.0
3  3faa81fc-9640-43d0-8b68-e5b06c65bfe6                3.0
4  09e24f3d-7191-4207-887c-98f31c6b59d2                3.0

In [113]:
result.to_csv('result.csv')